import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "@/components/home/header/Header";
import Introduce from "@/components/home/introduce/Introduce";
import WhyLevelUp from "@/components/home/whyLevelUp/WhyLevelUp";
import "react-slideshow-image/dist/styles.css";
import Articles from "@/components/home/articles/Articles";
import Plans from "@/components/home/plans/Plans";
import Footer from "@/components/global/Footer/Footer";
import Layout from "@/components/global/Layout/Layout";
import Features from "@/components/home/features/Features";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App2</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<Header />
				<Introduce />
				<WhyLevelUp />
				<Articles />
				<Features />
				<Plans />
			</Layout>
		</>
	);
}
