import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "@/components/home/header/Header";
import Features from "@/components/home/features/Features";
import WhyLevelUp from "@/components/home/whyLevelUp/WhyLevelUp";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App2</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main className="overflow-hidden">
				<Features />
				<WhyLevelUp />
			</main>
		</>
	);
}
